name: ldk_node
description: A ready-to-go Lightning node library built using LDK and BDK.
version: 0.3.0
homepage: https://github.com/LtbLightning/ldk-node-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.18.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.0.0
  freezed_annotation: ^2.2.0
  meta: ^1.12.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^12.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.8
  lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
