name: ldk_node
description: A ready-to-go Lightning node library built using LDK and BDK.
version: 0.1.2
homepage: https://github.com/LtbLightning/ldk-node-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.1
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">1.82.0 <= 1.82.1"
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  uuid: ^3.0.7
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^9.0.0
  build_runner: ^2.4.4
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.ldk.f.ldk_node
        pluginClass: LdkNodePlugin
      ios:
        pluginClass: LdkNodePlugin
