name: ldk_node
description: A ready-to-go Lightning node library built using LDK and BDK.
version: 0.5.0
homepage: https://github.com/LtbLightning/ldk-node-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: "^2.11.1"
  freezed_annotation: ^3.1.0
  meta: ^1.15.0
  path_provider: ^2.1.5
  flutter_riverpod: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffi: ^2.1.3
  ffigen: ^13.0.0
  freezed: ^3.2.0
  build_runner: ^2.4.8
  lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
